server:
  port: 8082

spring:
  datasource:
    url: "jdbc:postgresql://ep-snowy-sea-a7ovq2o7-pooler.ap-southeast-2.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require"
    username: ***REMOVED***
    password: ***REMOVED***
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  ai:
    google:
      genai:
        api-key: "${GEMINI_API_KEY}"
        chat:
          options:
            model: "gemini-2.5-flash"

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

jwt:
  token:
    secret: "@#^&*(*&$%@!~~!ELEC5620_AI_Trip_Assistant_@#$%^&*()_+"
    expireTime: 1800000

feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
        loggerLevel: BASIC