server:
  port: 8082

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  ai:
    openai:
      api-key: "${OPENAI_API_KEY}"
      model-name: "gpt-4o-mini"
      temperature: 0.7
      chat-completions-url: https://api.openai.com/v1/chat/completions
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

jwt:
  token:
    secret: "@#^&*(*&$%@!~~!ELEC5620_AI_Trip_Assistant_@#$%^&*()_+"
    expireTime: 3600000

aws:
  region: ap-southeast-2
  accesskeyId: "${AWS_ACCESS_KEY_ID}"
  secretAccessKey: "${AWS_SECRET_ACCESS_KEY}"
  s3:
    bucket-name: buckets-zihang
    dir-name: elec5620-stage2
    cdn: awscdn.dingzh.cc

sendgrid:
  api-key: "${SENDGRID_API_KEY}"
  from: "dingzh157@gmail.com"

frontend:
  base-url: "http://localhost:5173"

default:
  avatar-url: "https://awscdn.dingzh.cc/elec5620-stage2/avatars/default_avatar.png"

openweather:
  api:
    key: "${OPENWEATHER_API_KEY}"

unsplash:
  access-key: "${UNSPLASH_API_KEY}"

google:
  maps:
    api-key: "${GOOGLE_MAPS_API_KEY}"

feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
        loggerLevel: BASIC

booking:
  base-url: http://localhost:8092/api/booking
